# Generated by Django 4.2 on 2024-09-06 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=10, unique=True
            ),
            preserve_default=False,
        ),
    ]
